Cutpix.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Cutpix.Domain.Models.Blog;
using Cutpix.Services.Interfaces;
using Cutpix.Web.AutoMapper;
using Cutpix.Web.ViewModels.Blog;

namespace Cutpix.WebUI.Controllers
{
    [RoutePrefix("posts")]
    public class BlogController : Controller
    {
        private readonly IPostService _postService;
        private readonly IFileService _fileService;

        public BlogController(IPostService postService, IFileService fileService)
        {
            if (postService == null)
                throw new ArgumentNullException(nameof(postService));
            if (fileService == null)
                throw new ArgumentNullException(nameof(fileService));

            this._postService = postService;
            this._fileService = fileService;
        }

        [HttpGet, Route]
        public ActionResult Posts(int pageSize = 10)
        {
            var result = _postService.GetLastPosts(DateTime.UtcNow, pageSize);
            var models = result.ConvertTo<IEnumerable<Post>, IEnumerable<PostSummaryViewModel>>();

            return View(models);
        }

        [HttpGet, Route("{permalink}")]
        public ActionResult PostDetails(string permalink)
        {
            var post = _postService.FindPostByLink(permalink);
            if (post == null)
                throw new HttpException(404, "404 Not Found");

            var model = post.ConvertTo<Post, PostDetailedViewModel>();

            return View(model);
        }

        [HttpGet, ChildActionOnly]
        public ActionResult LastPost()
        {
            var model = _postService.GetLastPost(DateTime.UtcNow).ConvertTo<Post, PostSummaryViewModel>();
            if (model != null)
                return PartialView("_LastPost", model);

            return new EmptyResult();
        }

        [HttpGet, Route("create"), Authorize]
        public ActionResult CreatePost()
        {
            var model = new NewPostFormViewModel();
            return View(model);
        }

        [HttpPost, Route("create"), Authorize]
        public ActionResult CreatePost(NewPostFormViewModel model)
        {
            var post = model.ConvertTo<NewPostFormViewModel, Post>();

            if (model.File != null)
                post.ImageId = _fileService.UploadFile(model.File.InputStream, model.File.FileName).ToString();

            _postService.AddNewPost(post);

            return RedirectToAction("Posts");
        }
    }
}

Cutpix.WebUI/Controllers/ContentBuilderController.cs
using System.Web;
using System.Web.Mvc;
using Cutpix.Web.ViewModels.Blog;

namespace Cutpix.WebUI.Controllers
{
    [Authorize]
    public class ContentBuilderController : Controller
    {
        [HttpGet]
        public PartialViewResult AddImage()
        {
            return PartialView("_AddContent", new ImageContentFormModel());
        }

        [HttpGet]
        public PartialViewResult AddText()
        {
            return PartialView("_AddContent", new TextContentViewModel());
        }

        [HttpGet, Authorize]
        public ActionResult AddContent(string contentType)
        {
            const string viewName = "_AddContent";

            switch (contentType)
            {
                case "text":
                    return PartialView(viewName, new TextContentViewModel());
                case "image":
                    return PartialView(viewName, new ImageContentFormModel());
                case "audio":
                //return PartialView(viewName, new AudioContent());
                default:
                    throw new HttpException(404, $"Content Type: {contentType} not found.");
            }
        }
    }
}

Cutpix.WebUI/Controllers/GalleryController.cs
using System;
using System.Web.Mvc;
using Cutpix.Services.Interfaces;

namespace Cutpix.WebUI.Controllers
{
    public class GalleryController : Controller
    {
        protected IFileService FileService { get; set; }

        public GalleryController(IFileService fileService)
        {
            if (fileService == null)
                throw new ArgumentNullException(nameof(fileService));

            this.FileService = fileService;
        }

        public string GetImage(string id)
        {
            if (id == null)
                return string.Empty;

            var bytes = FileService.GetFileBytes(id);
            return $"data:image/png;base64,{Convert.ToBase64String(bytes)}";
        }

        public FileContentResult Image(string id)
        {
            if (id == null)
                throw new ArgumentNullException(nameof(id));

            var bytes = FileService.GetFileBytes(id);
            return File(bytes, "image/jpeg");
        }

        [HttpPost]
        public JsonResult JsonFilePreview()
        {
            var file = Request.Files["FileUpload"];

            if (file == null) return Json(null, JsonRequestBehavior.DenyGet);

            byte[] buffer;
            using (var fileStream = file.InputStream)
            {
                buffer = new byte[fileStream.Length];
                fileStream.Read(buffer, 0, (int) fileStream.Length);
            }

            return new JsonResult
            {
                Data = new {file.FileName, FileData = Convert.ToBase64String(buffer)},
                JsonRequestBehavior = JsonRequestBehavior.DenyGet,
                MaxJsonLength = int.MaxValue
            };
        }
    }
}

Cutpix.WebUI/Views/Blog/CreatePost.cshtml
@model Cutpix.Web.ViewModels.Blog.NewPostFormViewModel

@{
    ViewBag.Title = "Новая запись";
}

@section head {
    @Styles.Render("//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css")
}

@section billboard {

    <section id="header" class="page-pusher">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title">
                        <h1>@ViewBag.Title</h1>
                        <span>Автор: @User.Identity.Name</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("CreatePost", "Blog", null, FormMethod.Post, new {enctype = "multipart/form-data"}))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Author", User.Identity.Name)
                <div class="widget">

                    <div class="switch-tabs">

                        <div class="tabs">
                            <span rel="general-case" class="active">Общая информация</span>
                            <span rel="content-case">Контент</span>
                        </div>

                        <div id="general-case" class="case active">
                            <div class="widget-content row">
                                <div class="col-md-6 col-xs-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Title)
                                        @Html.EditorFor(m => m.Title)
                                    </div>
                                </div>
                                <div class="col-md-6 col-xs-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Permalink)
                                        @Html.EditorFor(m => m.Permalink)
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.EditorFor(m => m.Description)
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-12">
                                    <div class="form-group">
                                        <div class="file">
                                            @Html.TextBoxFor(m => m.File, new {@class = "inputfile", type = "file", accept = "image/x-png, image/jpeg"})
                                            @Html.LabelFor(m => m.File)
                                            <span id="display-filename"></span>
                                            <span class="toggler font-icon fa fa-toggle-off"></span>
                                        </div>
                                        <div class="post-cover-wrapper collapsed"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="content-case" class="case">
                            @Ajax.ActionLink("Добавить Text", "AddText", "ContentBuilder",
                                new AjaxOptions {HttpMethod = "GET", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "content-list"})
                            @Ajax.ActionLink("Добавить Image", "AddImage", "ContentBuilder",
                                new AjaxOptions {HttpMethod = "GET", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "content-list"})
                            <div id="content-list"></div>
                        </div>

                    </div>

                </div>
                <div class="form-actions">
                    <input class="btn btn-success" type="submit" value="Опубликовать"/>
                </div>
            }
        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/custom")
    @Scripts.Render("~/js/blog.create-post.js")
}

@section init {
    <script type="text/javascript">
        $(document).ready(function() {
            main.init({
                "previewUrl": "@Url.Action("JsonFilePreview", "Gallery")"
            });
        });
    </script>
}

Cutpix.WebUI/Views/Blog/PostDetails.cshtml
@model Cutpix.Web.ViewModels.Blog.PostDetailedViewModel

@{
    ViewBag.Title = Model.Title;
}


<section class="leader-block leader-block-featured-image" style="background-image: url(@Html.Action("GetImage", "Gallery", new {id = Model.ImageId}))">
    <div class="container">
        <div class="leader-block-content clearfix">
            <div class="leader-block-content-inside">
                <header class="entry-header-leader-block">
                    <h1 class="entry-title">@Model.Title</h1>
                </header>
                <div class="entry-meta">@Model.Description</div>
            </div>
        </div>
    </div>
    <div class="leader-block-overlay"></div>
    <div class="leader-block-perspective"></div>
</section>

<section id="content" class="site-content">
    <div class="container">
        <div class="row">
            <div id="primary" class="content-area col-lg-12">
                <main id="main">
                    <article>
                        <time class="date">@Model.Created.ToString("f")</time>

                        @Html.DisplayFor(m => m.ContentList)

                        @if (Model.Tags.Count != 0)
                        {
                            <div class="article-tags">
                                <mark>@Html.NameFor(m => m.Tags) > @string.Join(", ", Model.Tags)</mark>
                            </div>
                        }
                    </article>
                </main>
            </div>
        </div>
    </div>
</section>

Cutpix.WebUI/Views/Blog/Posts.cshtml
@model IEnumerable<Cutpix.Web.ViewModels.Blog.PostSummaryViewModel>

@{
    ViewBag.Title = "List of posts";
}

@section billboard {

    <section id="header" class="page-pusher">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title">
                        <h1>@ViewBag.Title</h1>
                        <span>Page Size: @Model.Count()</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

@foreach (var article in Model)
{
    <section id="@article.Id">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <article class="info">
                        <h3 class="article-title">
                            <a href="@Url.Action("PostDetails", new {permalink = article.Permalink})">@article.Title</a>
                        </h3>
                        <details class="description">
                            <summary>Description</summary>
                            <p>@article.Description</p>
                        </details>
                    </article>
                </div>
            </div>
        </div>
    </section>
}

Cutpix.WebUI/Views/Blog/_LastPost.cshtml
@model Cutpix.Web.ViewModels.Blog.PostSummaryViewModel

<section id="billboard" class="user-profile">
    <div id="cover">
        <div class="entry-picture" style="background-image: url(@Url.Action("Image", "Gallery", new {id = Model.ImageId}))"></div>

        <div class="bottom">
            <div class="fader">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="entry-summary">
                                <h5 class="feature-heading">@Html.ActionLink(Model.Category, "List", "Category", null, new {permalink = Model.Category})</h5>
                                <h1 class="entry-title">
                                    @Html.ActionLink(Model.Title, "PostDetails", "Blog", new {permalink = Model.Permalink}, null)
                                </h1>
                                <p class="entry-published">@Model.Created.ToString("f")</p>
                                <p class="entry-description">@Model.Description</p>
                            </div>

                            @Html.Partial("_ProfileSummary")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>